create table public.ortex (
	transactionid integer PRIMARY KEY,
	gvkey integer,
	companyname varchar(128),
	companyisin varchar(128),
	companysedol varchar(128),
	insiderid INTEGER,
	insidername varchar(128),
	insiderrelation VARCHAR(128),
	insiderlevel VARCHAR(128),
	connectiontype VARCHAR(128),
	connectedinsidername VARCHAR(128),
	connectedinsiderposition VARCHAR(128),
	transactiontype VARCHAR(128),
	transactionlabel VARCHAR(128),
	iid VARCHAR(128),
	securityisin VARCHAR(128),
	securitysedol VARCHAR(128),
	securitydisplay VARCHAR(128),
	assetclass VARCHAR(128),
	shares INTEGER,
	inputdate INTEGER,
	tradedate INTEGER,
	maxtradedate double PRECISION,
	price double PRECISION,
	maxprice double PRECISION,
	value double PRECISION,
	currency VARCHAR(128),
	valueeur double PRECISION,
	unit VARCHAR(128),
	correctedtransactionid double PRECISION,
	source VARCHAR(128),
	tradesignificance INTEGER,
	holdings double PRECISION,
	filingurl VARCHAR(128),
	exchange VARCHAR(128)
);